"""empty message

Revision ID: 27d9afa1687a
Revises: f514b6217d7f
Create Date: 2023-09-21 09:26:23.467057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d9afa1687a'
down_revision = 'f514b6217d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['apellido'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
