"""empty message

Revision ID: 397b572d0a96
Revises: 5238917aa9f5
Create Date: 2023-09-20 23:33:14.541570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397b572d0a96'
down_revision = '5238917aa9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen_servicio')
    op.drop_table('categoria')
    op.drop_table('servicio')
    op.drop_table('usuario')
    op.drop_table('proveedor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('proveedor_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('rut', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('comuna', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('red_social', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contrasena', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='proveedor_pkey'),
    sa.UniqueConstraint('correo', name='proveedor_correo_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey'),
    sa.UniqueConstraint('correo', name='usuario_correo_key'),
    sa.UniqueConstraint('nombre', name='usuario_nombre_key')
    )
    op.create_table('servicio',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('servicio_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('detalle', sa.VARCHAR(length=3000), autoincrement=False, nullable=True),
    sa.Column('precio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proveedor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cobertura', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name='servicio_categoria_id_fkey'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name='servicio_proveedor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='servicio_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('categoria',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categoria_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categoria_pkey'),
    sa.UniqueConstraint('nombre', name='categoria_nombre_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('imagen_servicio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('secure_url', sa.VARCHAR(length=400), autoincrement=False, nullable=False),
    sa.Column('servicio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], name='imagen_servicio_servicio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='imagen_servicio_pkey')
    )
    # ### end Alembic commands ###
