"""empty message

Revision ID: 85d420965e4c
Revises: 99708ae2dc9f
Create Date: 2023-09-20 23:16:04.866842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d420965e4c'
down_revision = '99708ae2dc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey'),
    sa.UniqueConstraint('correo', name='usuario_correo_key'),
    sa.UniqueConstraint('nombre', name='usuario_nombre_key')
    )
    # ### end Alembic commands ###
